on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: asachs/zmk/.github/workflows/build-user-config.yml@corne-ish-zen-v2
    with:
      build_matrix_path: zen/build.yml
      config_path: zen
